#!/usr/bin/env bash
# Run /blog-calibrate locally and email the result.
# Runs from cron on the 1st of each month at 9am local.

set -uo pipefail

LOG=/home/jeremy/.local/state/blog-monthly-calibrate/calibrate.log
mkdir -p "$(dirname "$LOG")"

YM=$(date +%Y-%m)
REPORT=/tmp/blog-calibrate-${YM}.txt
EMAIL_SCRIPT=/home/jeremy/.claude/skills/email/scripts/send-email.cjs

echo "[$(date -Is)] Starting calibration run for ${YM}" >> "$LOG"

# Run /blog-calibrate via headless Claude Code.
# `claude -p` runs a one-shot prompt and exits.
cd /home/jeremy/000-projects/blog/startaitools || { echo "[$(date -Is)] FATAL: cd to blog dir failed" >> "$LOG"; exit 1; }
if ! /usr/bin/timeout 300 claude -p "/blog-calibrate" --dangerously-skip-permissions > "$REPORT" 2>&1; then
  echo "[$(date -Is)] claude -p exited non-zero — emailing anyway" >> "$LOG"
fi

# Email the report (whatever happened — success or partial)
size=$(wc -c < "$REPORT" 2>/dev/null || echo 0)
echo "[$(date -Is)] Report size: ${size} bytes" >> "$LOG"

subject="Monthly blog calibration: ${YM}"
body="Calibration report for ${YM}.

Generated by /home/jeremy/000-projects/blog/startaitools/scripts/blog/blog-monthly-calibrate.sh
Source: /home/jeremy/000-projects/blog/startaitools/.claude/skills/blog-backfill/methodology/decisions.jsonl

================================================================================

$(cat "$REPORT")
"

if node "$EMAIL_SCRIPT" --to jeremy@intentsolutions.io --subject "$subject" --body "$body" >> "$LOG" 2>&1; then
  echo "[$(date -Is)] Emailed report" >> "$LOG"
else
  echo "[$(date -Is)] EMAIL FAILED — report kept at $REPORT" >> "$LOG"
fi

# ntfy push (low priority — monthly summary, not urgent)
NTFY_TOPIC=$(cat /home/jeremy/.ntfy-topic 2>/dev/null)
if [ -n "$NTFY_TOPIC" ]; then
  curl -s -H "Title: Monthly blog calibration done" -H "Priority: low" -H "Tags: chart_with_upwards_trend" \
    -d "${YM} report emailed" \
    "https://ntfy.sh/$NTFY_TOPIC" >> "$LOG" 2>&1 || true
fi
