baseURL = "https://startaitools.com/"
title = "Intent Solutions Inc"
theme = "hugo-book"
languageCode = "en-us"
copyright = "© 2025 Intent Solutions Inc"

# Book configuration
disablePathToLower = true
enableGitInfo = true

# Needed for code syntax highlighting
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  BookTheme = "auto"

  # Site subtitle
  subtitle = "Deploy AI solutions in days, not months"

  # (Optional, default true) Controls table of contents visibility on right side of pages.
  BookToC = true

  # (Optional, default none) Set the path to a logo for the book.
  # BookLogo = "/logo.png"

  # (Optional, default docs) Specify root page to render child pages as menu.
  BookSection = "docs"

  # Set source repository location for Edit links
  BookRepo = "https://github.com/jeremylongshore/startaitools.com"

  # (Optional, default "commit") Specifies commit portion of the link to the source repository.
  BookCommitPath = "commit"

  # Enable "Edit this page" links for 'doc' page type.
  BookEditPath = "edit/main"

  # (Optional, default January 2, 2006) Configure the date format used on the pages
  BookDateFormat = "January 2, 2006"

  # (Optional, default true) Enables search
  BookSearch = true

  # (Optional, default true) Enables comments template on pages
  BookComments = false

  # (Optional, default false) Enable/disable Previous/Next navigation
  BookMenuBundle = "/menu"

  # (Optional, default true) Show previous/next navigation
  BookPortableLinks = true

  # Custom CSS
  customCSS = ["css/custom.css"]

# Multi-lingual mode config
[languages]
  [languages.en]
    languageName = "English"
    weight = 1

[menu]
  [[menu.before]]
    name = "GitHub"
    url = "https://github.com/jeremylongshore"
    weight = 10

  [[menu.after]]
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.after]]
    name = "Contact"
    url = "/contact/"
    weight = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 6
    startLevel = 2
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4

# Enable robots.txt
enableRobotsTXT = true

# Pagination
[pagination]
  pagerSize = 10

# Output formats
[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]

# Privacy settings
[privacy]
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true