baseURL = "https://startaitools.com/"
title = "intent solutions io"
theme = "archie"
languageCode = "en-us"
copyright = "© 2025 intent solutions io"

# Google Analytics - Replace with your tracking ID
googleAnalytics = "G-XXXXXXXXXX"

# Needed for code syntax highlighting
pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsStyle = "monokai"

[params]
  # Archie theme specific params
  mode = "auto" # color mode (light/dark/auto)
  useCDN = false
  subtitle = "Deploy AI solutions in days, not months"

  # SEO Configuration
  description = "Learn AI implementation with real-world guides and templates"
  keywords = ["AI development", "machine learning", "technical guides", "automation"]
  author = "intent solutions io"

  # Open Graph defaults
  images = ["/images/og-default.png"]

  # Custom CSS
  customCSS = ["css/custom.css"]

  # Social links for Archie theme
  [[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/jeremylongshore"

# Menu configuration for Archie theme
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Research"
url = "/research"
weight = 4

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 5

[[menu.main]]
name = "Contact"
url = "/contact"
weight = 6

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 6
    startLevel = 2
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 4

# Enable robots.txt
enableRobotsTXT = true

# Pagination
[pagination]
  pagerSize = 10

# Output formats
[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]

# Privacy settings
[privacy]
  [privacy.googleAnalytics]
    disable = false
    anonymizeIP = true
    respectDoNotTrack = true
  [privacy.instagram]
    disable = true
  [privacy.x]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true