[build]
  command = "hugo --gc --minify --cleanDestinationDir"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.150.0"
  HUGO_ENABLEGITINFO = "true"
  HUGO_ENV = "production"
  NODE_VERSION = "18"
  TZ = "America/Chicago"

[[redirects]]
  from = "http://startaitools.com/*"
  to = "https://startaitools.com/:splat"
  status = 301
  force = true