[build]
  command = "hugo --gc --minify --cleanDestinationDir"
  publish = "public"

[dev]
  command = "hugo server -D --bind 0.0.0.0"
  port = 8889
  targetPort = 1313
  framework = "hugo"
  autoLaunch = true

[build.environment]
  HUGO_VERSION = "0.149.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  NODE_VERSION = "18"

[[redirects]]
  from = "http://startaitools.com/*"
  to = "https://startaitools.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.startaitools.com/*"
  to = "https://startaitools.com/:splat"
  status = 301
  force = true

[context.split1]
  command = "hugo --gc --minify --enableGitInfo && npx -y pagefind --site public"

[context.split1.environment]
  HUGO_VERSION = "0.149.1"
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL && npx -y pagefind --site public"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.149.1"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL && npx -y pagefind --site public"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.149.1"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"