[build]
  command = "hugo --gc --minify --cleanDestinationDir"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.150.0"
  HUGO_ENABLEGITINFO = "true"
  HUGO_ENV = "production"
  NODE_VERSION = "18"
  TZ = "America/Chicago"

[[redirects]]
  from = "http://startaitools.com/*"
  to = "https://startaitools.com/:splat"
  status = 301
  force = true

# Cache control headers to prevent stale content
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/posts/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/about/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/projects/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/research/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Force deploy: 2025-10-07 20:52:00 - Homepage cache bust